name: Deploy Prometheus config to EC2

on:
  push:
    branches:
      - dev
    paths:
      - prometheus.yml
      - alertmanager.yml

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH agent with private key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_LAPTOP }}

      - name: Copy Prometheus and Alertmanager config files to EC2
        run: |
          rsync prometheus.yml alertmanager.yml ec2-user@YOUR_EC2_IP:/opt /prometheus/

      - name: Restart Prometheus and Alertmanager services
        run: |
          ssh ec2-user@YOUR_EC2_IP 'sudo systemctl restart prometheus && sudo systemctl restart alertmanager'