global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
      monitor: 'example'

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets: ['localhost:9093']
      labels:
            environment: "DEV"

rule_files:
  # - "prometheus.rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    metrics_path: /metrics
    scrape_interval: 60s
    scheme: http
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          environment: "DEV"
    relabel_configs:
      - source_labels: [__address__]
        regex: '([^:]+):\d+'
        target_label: instance
        replacement: '\${1}'
      - source_labels: [instance]
        regex: '^(\d+\.\d+)\.\d+\.\d+'
        target_label: shortname
        replacement: '\${1}'
  - job_name: 'pushgateway'
    honor_labels: true
    static_configs:
      - targets: ['localhost:9091']
        labels:
            environment: "DEV"
  
  - job_name: 'SECOUREO - NODE_EXPORTER'
    honor_labels: true
    static_configs:
      - targets: ['grafana.secoureo.com:9100']
        labels:
            environment: "DEV"

  ###TEST###